sudo: required
language: node_js
node_js:
  - stable
  - 4.2
services:
  - mongodb
  - docker
before_script:
  - npm install -g npm@latest
  - npm install
script:
  - npm test
after_script:
  - npm run coveralls

before_install:
  - docker build -t malthestougaard/mstdemo .
